# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:           Alexander Tishin
description:     Economist, Bank of Russia
url: "http://avtishin.github.io/"


author:
  name:           Alexander Tishin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap