# Dependencies
# markdown:         redcarpet
highlighter:      rouge
permalink: /

# Permalinks
permalink:        pretty

# Setup
title:           'Alexander Tishin - personal page'
description:     'My personal site, Economist, Bank of Russia'
tagline:          'Personal page, economics, macroecnomics'
url: 'http://avtishin.github.io/'


author:
  name:           Alexander Tishin

paginate:         5
paginate_path: "thoughts/page:num/"
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/avtishin/avtishin.github.io
  
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap